# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [9]:
import numpy as np




### 2. Print the NUMPY version and the configuration.


In [2]:
print(np.__version__)
print(np.__config__)


2.4.6
<module 'numpy.__config__' from 'c:\\Users\\Administrator\\anaconda3\\Lib\\site-packages\\numpy\\__config__.py'>


### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [8]:
# Random integers between 0 and 99
import numpy as np

#Generate a random 3D NumPy integer array with dimensions 2 x 3 x 5
a = np.random.randint(0, 100, size=(2, 3, 5)) 

#Generate a random 3D NumPy floating array with dimensions 2 x 3 x 5
b = np.random.random((2, 3, 5))

# By using randn function
c= np.random.randn(2,3,5)


# by using random_sample method
d = np.random.random_sample((2, 3, 5))



### 4. Print a.


In [7]:
#print integer array
print(a)

#print integer array
print(b)

print(c)
print(d)

print(a.shape)
print(b.shape) 
print(c.shape)



[[[68 45 86 64 35]
  [ 9 29 46 19 30]
  [14  0 42 72 42]]

 [[95 21 16 95 15]
  [31 52 37 70 48]
  [97 53 88 60 20]]]
[[[0.9395078  0.97262214 0.11293747 0.35453738 0.92070784]
  [0.32171573 0.97479916 0.55638549 0.77273063 0.46336863]
  [0.39699925 0.2600528  0.62235324 0.51034033 0.49646423]]

 [[0.50560195 0.47320392 0.99137756 0.45647169 0.33067888]
  [0.90790692 0.54742512 0.2014054  0.3121467  0.72505568]
  [0.31165045 0.349307   0.58684917 0.44244126 0.85604151]]]
[[[ 0.98504999  0.24215799  0.07295767 -0.86862572 -0.53597893]
  [-0.3899071  -1.85050912 -0.89103945 -0.0876165  -2.05389486]
  [ 0.43774117 -1.49810501 -0.34989204 -1.58395585  2.34139918]]

 [[ 0.48126648  0.70441647 -0.27918705  0.13469927  0.17226556]
  [-0.31853315  0.6351362   0.6307948  -0.14066362  1.13637039]
  [ 0.27460166  1.73583368 -0.76031805 -0.26663286  0.48281422]]]
0.3414178679865171
(2, 3, 5)
(2, 3, 5)
(2, 3, 5)


### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [33]:
#create 5x2x3 array filled with 1.0 (floats)
b =np.ones((5, 2, 3))

#create 5x2x3 array filled with 1(int)
b =np.ones((5, 2, 3),dtype=int)



### 6. Print b.


In [24]:
##printing the array b
display(b)
print(b)

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]



### 7. Do a and b have the same size? How do you prove that in Python code?


In [17]:
# Recreating arrays from your previous steps
a = np.random.randint(0, 100, size=(2, 3, 5))
b = np.ones((5, 2, 3))

# Print the sizes directly
print(f"Total elements in a: {a.size}")  
print(f"Total elements in b: {b.size}")  

# Programmatically prove they are equal
print(a.size == b.size)  # Output: True


Total elements in a: 30
Total elements in b: 30
True



### 8. Are you able to add a and b? Why or why not?


In [19]:
#No we can't add a and b because both array shape is different 
print(a.shape)
print(b.shape)


(2, 3, 5)
(5, 2, 3)




### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [26]:
# Actual shape of b 
print(b.shape)

##Transpose array b (2,3,5)
c=b.transpose(1,2,0)
print(c.shape)


(5, 2, 3)
(2, 3, 5)



### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [ ]:
#adding 3dimensional arrays 
# both array of same shape
d = a + c



### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [32]:
#print a
display(a)
print(a.dtype)
print("---------------------------")

# print d
display(d)
print(d.dtype)


array([[[ 7, 47, 56, 19,  9],
        [53, 97, 77, 77, 10],
        [82, 70, 82, 11, 48]],

       [[26, 61, 87, 50, 57],
        [42, 48, 77, 29, 64],
        [87, 58, 55,  0, 35]]], dtype=int32)

int32
---------------------------


array([[[ 8., 48., 57., 20., 10.],
        [54., 98., 78., 78., 11.],
        [83., 71., 83., 12., 49.]],

       [[27., 62., 88., 51., 58.],
        [43., 49., 78., 30., 65.],
        [88., 59., 56.,  1., 36.]]])

float64



### 12. Multiply a and c. Assign the result to e.


In [30]:
#Multiply a and c
e= a * c



### 13. Does e equal to a? Why or why not?


In [35]:
#print e
display(e)
print(e.dtype)
print("---------------------------")
# print a
display(a)
print(a.dtype)
print("---------------------------")

print(a == e)

array([[[ 7., 47., 56., 19.,  9.],
        [53., 97., 77., 77., 10.],
        [82., 70., 82., 11., 48.]],

       [[26., 61., 87., 50., 57.],
        [42., 48., 77., 29., 64.],
        [87., 58., 55.,  0., 35.]]])

float64
---------------------------


array([[[ 7, 47, 56, 19,  9],
        [53, 97, 77, 77, 10],
        [82, 70, 82, 11, 48]],

       [[26, 61, 87, 50, 57],
        [42, 48, 77, 29, 64],
        [87, 58, 55,  0, 35]]], dtype=int32)

int32
---------------------------
[[[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]

 [[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]]




### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [39]:
#finding the max, min and mean values
d_max=np.max(d)
d_min =np.min(d)
d_mean =np.mean(d)



### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [42]:
#creating a array (2,3,5)
f = np.empty((2,3,5))




### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [45]:
##Assign 0 for minimum values
f[d == d_min] = 0

# Assign 25 for values between min and mean
f[(d > d_min)& (d < d_mean)] = 25

# Assign 50 for values equal to mean
f[d == d_mean] =50

# Assign 75 for values between mean and max
f[(d > d_mean) & (d <d_max)] =75

# Assign 100 for maximum values
f[d == d_max] = 100






### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [46]:
#print d
print(d)

# print f
print(f)

[[[ 8. 48. 57. 20. 10.]
  [54. 98. 78. 78. 11.]
  [83. 71. 83. 12. 49.]]

 [[27. 62. 88. 51. 58.]
  [43. 49. 78. 30. 65.]
  [88. 59. 56.  1. 36.]]]
[[[ 25.  25.  75.  25.  25.]
  [ 75. 100.  75.  75.  25.]
  [ 75.  75.  75.  25.  25.]]

 [[ 25.  75.  75.  25.  75.]
  [ 25.  25.  75.  25.  75.]
  [ 75.  75.  75.   0.  25.]]]


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [48]:
# Create a 2x3x5 array restricted to single characters
# U1 -> is unicode String can store single character
f_char = np.empty((2, 3, 5), dtype='U1')

#  Immediately overwrite everything with a truly empty string character
f_char[:] = ""

In [49]:
##Assign 0 for minimum values
f_char[d == d_min] = 'NuLL'

# Assign 25 for values between min and mean
f_char[(d > d_min)& (d < d_mean)] = 'A'

# Assign 50 for values equal to mean
f_char[d == d_mean] ='B'

# Assign 75 for values between mean and max
f_char[(d > d_mean) & (d <d_max)] ='C'

# Assign 100 for maximum values
f_char[d == d_max] = 'D'

In [51]:
# print 
print(d)
print(f_char)

[[[ 8. 48. 57. 20. 10.]
  [54. 98. 78. 78. 11.]
  [83. 71. 83. 12. 49.]]

 [[27. 62. 88. 51. 58.]
  [43. 49. 78. 30. 65.]
  [88. 59. 56.  1. 36.]]]
[[['A' 'A' 'C' 'A' 'A']
  ['C' 'D' 'C' 'C' 'A']
  ['C' 'C' 'C' 'A' 'A']]

 [['A' 'C' 'C' 'A' 'C']
  ['A' 'A' 'C' 'A' 'C']
  ['C' 'C' 'C' 'N' 'A']]]
